### Домашнее задание «Библиотека numpy. Вычислительные задачи».

#### Задание 1.
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).



In [2]:
import numpy as np

In [11]:
N = 15
data = np.arange(N)[::-1]
data

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### Задание 2.
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.


In [20]:
N = 7
diag_n = np.arange(N)[::-1]

In [21]:
np.diag(diag_n)

array([[6, 0, 0, 0, 0, 0, 0],
       [0, 5, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [22]:
diag_sum = diag_n.sum()
diag_sum

21

#### Задание 3.
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [24]:
from numpy import linalg

In [26]:
q1 = np.array([[4,2,1],[1,3,0],[0,5,4]])
q2 = np.array([4,12,-3])
s = linalg.solve(q1,q2)
s

array([ 0.46666667,  3.84444444, -5.55555556])

In [30]:
np.allclose(np.dot(q1,s),q2)

True

#### Задание 4.

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [36]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ],
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [47]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [65]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [66]:
users_similarity = {}
user_id = 1
for user in users_stats:
    similarity = cosine(next_user_stats, user)
    users_similarity[user_id] = similarity
    user_id +=1

In [67]:
similar_user = max(users_similarity, key=lambda key: users_similarity[key])
print(f'Самый похожий пользователь: {similar_user}')

Самый похожий пользователь: 8
